//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace SilverlightApplication2.WS_SYSDATEService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="P_OUT-VARCHAR2-OUT", Namespace="http://xmlns.oracle.com/orawsv/MTIDAE_INTEGRACION/WS_SYSDATE")]
    public partial class P_OUTVARCHAR2OUT : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/orawsv/MTIDAE_INTEGRACION/WS_SYSDATE", ConfigurationName="WS_SYSDATEService.WS_SYSDATEPortType")]
    public interface WS_SYSDATEPortType {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="WS_SYSDATE", ReplyAction="*")]
        System.IAsyncResult BeginWS_SYSDATE(SilverlightApplication2.WS_SYSDATEService.WS_SYSDATERequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEResponse EndWS_SYSDATE(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_SYSDATEInput", WrapperNamespace="http://xmlns.oracle.com/orawsv/MTIDAE_INTEGRACION/WS_SYSDATE", IsWrapped=true)]
    public partial class WS_SYSDATERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="P_OUT-VARCHAR2-OUT", Namespace="http://xmlns.oracle.com/orawsv/MTIDAE_INTEGRACION/WS_SYSDATE", Order=0)]
        public SilverlightApplication2.WS_SYSDATEService.P_OUTVARCHAR2OUT P_OUTVARCHAR2OUT;
        
        public WS_SYSDATERequest() {
        }
        
        public WS_SYSDATERequest(SilverlightApplication2.WS_SYSDATEService.P_OUTVARCHAR2OUT P_OUTVARCHAR2OUT) {
            this.P_OUTVARCHAR2OUT = P_OUTVARCHAR2OUT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WS_SYSDATEOutput", WrapperNamespace="http://xmlns.oracle.com/orawsv/MTIDAE_INTEGRACION/WS_SYSDATE", IsWrapped=true)]
    public partial class WS_SYSDATEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/orawsv/MTIDAE_INTEGRACION/WS_SYSDATE", Order=0)]
        public string P_OUT;
        
        public WS_SYSDATEResponse() {
        }
        
        public WS_SYSDATEResponse(string P_OUT) {
            this.P_OUT = P_OUT;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_SYSDATEPortTypeChannel : SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SYSDATECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public WS_SYSDATECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SYSDATEPortTypeClient : System.ServiceModel.ClientBase<SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType>, SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType {
        
        private BeginOperationDelegate onBeginWS_SYSDATEDelegate;
        
        private EndOperationDelegate onEndWS_SYSDATEDelegate;
        
        private System.Threading.SendOrPostCallback onWS_SYSDATECompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WS_SYSDATEPortTypeClient() {
        }
        
        public WS_SYSDATEPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_SYSDATEPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SYSDATEPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SYSDATEPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<WS_SYSDATECompletedEventArgs> WS_SYSDATECompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType.BeginWS_SYSDATE(SilverlightApplication2.WS_SYSDATEService.WS_SYSDATERequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginWS_SYSDATE(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginWS_SYSDATE(SilverlightApplication2.WS_SYSDATEService.P_OUTVARCHAR2OUT P_OUTVARCHAR2OUT, System.AsyncCallback callback, object asyncState) {
            SilverlightApplication2.WS_SYSDATEService.WS_SYSDATERequest inValue = new SilverlightApplication2.WS_SYSDATEService.WS_SYSDATERequest();
            inValue.P_OUTVARCHAR2OUT = P_OUTVARCHAR2OUT;
            return ((SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType)(this)).BeginWS_SYSDATE(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEResponse SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType.EndWS_SYSDATE(System.IAsyncResult result) {
            return base.Channel.EndWS_SYSDATE(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndWS_SYSDATE(System.IAsyncResult result) {
            SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEResponse retVal = ((SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType)(this)).EndWS_SYSDATE(result);
            return retVal.P_OUT;
        }
        
        private System.IAsyncResult OnBeginWS_SYSDATE(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SilverlightApplication2.WS_SYSDATEService.P_OUTVARCHAR2OUT P_OUTVARCHAR2OUT = ((SilverlightApplication2.WS_SYSDATEService.P_OUTVARCHAR2OUT)(inValues[0]));
            return this.BeginWS_SYSDATE(P_OUTVARCHAR2OUT, callback, asyncState);
        }
        
        private object[] OnEndWS_SYSDATE(System.IAsyncResult result) {
            string retVal = this.EndWS_SYSDATE(result);
            return new object[] {
                    retVal};
        }
        
        private void OnWS_SYSDATECompleted(object state) {
            if ((this.WS_SYSDATECompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.WS_SYSDATECompleted(this, new WS_SYSDATECompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void WS_SYSDATEAsync(SilverlightApplication2.WS_SYSDATEService.P_OUTVARCHAR2OUT P_OUTVARCHAR2OUT) {
            this.WS_SYSDATEAsync(P_OUTVARCHAR2OUT, null);
        }
        
        public void WS_SYSDATEAsync(SilverlightApplication2.WS_SYSDATEService.P_OUTVARCHAR2OUT P_OUTVARCHAR2OUT, object userState) {
            if ((this.onBeginWS_SYSDATEDelegate == null)) {
                this.onBeginWS_SYSDATEDelegate = new BeginOperationDelegate(this.OnBeginWS_SYSDATE);
            }
            if ((this.onEndWS_SYSDATEDelegate == null)) {
                this.onEndWS_SYSDATEDelegate = new EndOperationDelegate(this.OnEndWS_SYSDATE);
            }
            if ((this.onWS_SYSDATECompletedDelegate == null)) {
                this.onWS_SYSDATECompletedDelegate = new System.Threading.SendOrPostCallback(this.OnWS_SYSDATECompleted);
            }
            base.InvokeAsync(this.onBeginWS_SYSDATEDelegate, new object[] {
                        P_OUTVARCHAR2OUT}, this.onEndWS_SYSDATEDelegate, this.onWS_SYSDATECompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType CreateChannel() {
            return new WS_SYSDATEPortTypeClientChannel(this);
        }
        
        private class WS_SYSDATEPortTypeClientChannel : ChannelBase<SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType>, SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType {
            
            public WS_SYSDATEPortTypeClientChannel(System.ServiceModel.ClientBase<SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEPortType> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginWS_SYSDATE(SilverlightApplication2.WS_SYSDATEService.WS_SYSDATERequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("WS_SYSDATE", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEResponse EndWS_SYSDATE(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEResponse _result = ((SilverlightApplication2.WS_SYSDATEService.WS_SYSDATEResponse)(base.EndInvoke("WS_SYSDATE", _args, result)));
                return _result;
            }
        }
    }
}
